sudo: false
language: rust
rust:
- 1.22.0  # Oldest supported
- stable
- beta
- nightly

os:
- linux
- osx
- windows

script:
- cargo check --verbose  # Ensure `bin` compiles
- cargo test --verbose

cache:
  cargo: true
